image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - a
  - b

build:
  stage: a
  script:
    - python -m build build
  artifacts:
    paths:
      - dist/*.whl

test-install:
  stage: b
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip instal dist/*.whl
