include: .gitlab-ci.pymodule.yml

variables:
  PACKAGE_NAME: gtkworker
  APT_PKG: libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0

.prep-script-extra: &prep-script-extra
  - python3 -m venv venv
  - . venv/bin/activate
  - if test -n "$TWINE_UPLOAD" ; then export PIP_EXTRA_INDEX_URL=$TWINE_REPOSITORY/simple/ ; fi
  - pip install --upgrade pip build wheel setuptools pytest
  - apt-get update
  - apt -y install $APT_PKG
  - pip install pygobject pytest

prep:
  extends: .prep
  script: *prep-script-extra

build:
  extends: .build

test-install:
  extends: .test-install

.gtk-test:
  extends: .cache-user
  stage: test

test:
  extends: .gtk-test
  script:
    - pip install dist/*.whl
    - pytest $PACKAGE_NAME

docs:
  extends: .docs
    
pages:
  extends: .pages

upload-successful:
  extends: .upload-successful


