include: .gitlab-ci.pymodule.yml

variables:
  PACKAGE_NAME: gtkworker

prep:
  extends: .prep

build:
  extends: .build

test-install:
  extends: .test-install

test:
  extends: .pytest

docs:
  extends: .docs
    
pages:
  extends: .pages

upload-successful:
  extends: .upload-successful


