include: .gitlab-ci.pymodule.yml

variables:
  PACKAGE_NAME: gtkworker
  APT_PKG: libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0

.prep-script-extra: &prep-script-extra:
  - apt-get update
  - apt -y install $APT_PKG
  - pip install pygobject pytest

prep:
  extends: .prep
  script: [ *prep-script-base, *prep-script-extra ]

build:
  extends: .build

test-install:
  extends: .test-install

.gtk-test:
  extends: .cache-user
  stage: test

test:
  extends: .gtk-test
  script:
    - pip install dist/*.whl
    - pytest $PACKAGE_NAME

docs:
  extends: .docs
    
pages:
  extends: .pages

upload-successful:
  extends: .upload-successful


